
package com.example.soap.ws.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LoanEligibilityIndicatorService", targetNamespace = "http://www.example.com/soap/ws/loanEligibility", wsdlLocation = "file:/C:/Users/bough/Desktop/TP2_client/spring-boot-soap-ws-client/src/main/resources/wsdl/loanEligibility.wsdl")
public class LoanEligibilityIndicatorService
    extends Service
{

    private final static URL LOANELIGIBILITYINDICATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOANELIGIBILITYINDICATORSERVICE_EXCEPTION;
    private final static QName LOANELIGIBILITYINDICATORSERVICE_QNAME = new QName("http://www.example.com/soap/ws/loanEligibility", "LoanEligibilityIndicatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/bough/Desktop/TP2_client/spring-boot-soap-ws-client/src/main/resources/wsdl/loanEligibility.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOANELIGIBILITYINDICATORSERVICE_WSDL_LOCATION = url;
        LOANELIGIBILITYINDICATORSERVICE_EXCEPTION = e;
    }

    public LoanEligibilityIndicatorService() {
        super(__getWsdlLocation(), LOANELIGIBILITYINDICATORSERVICE_QNAME);
    }

    public LoanEligibilityIndicatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOANELIGIBILITYINDICATORSERVICE_QNAME, features);
    }

    public LoanEligibilityIndicatorService(URL wsdlLocation) {
        super(wsdlLocation, LOANELIGIBILITYINDICATORSERVICE_QNAME);
    }

    public LoanEligibilityIndicatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOANELIGIBILITYINDICATORSERVICE_QNAME, features);
    }

    public LoanEligibilityIndicatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanEligibilityIndicatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoanEligibilityIndicator
     */
    @WebEndpoint(name = "LoanEligibilityIndicatorSoap11")
    public LoanEligibilityIndicator getLoanEligibilityIndicatorSoap11() {
        return super.getPort(new QName("http://www.example.com/soap/ws/loanEligibility", "LoanEligibilityIndicatorSoap11"), LoanEligibilityIndicator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanEligibilityIndicator
     */
    @WebEndpoint(name = "LoanEligibilityIndicatorSoap11")
    public LoanEligibilityIndicator getLoanEligibilityIndicatorSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/soap/ws/loanEligibility", "LoanEligibilityIndicatorSoap11"), LoanEligibilityIndicator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOANELIGIBILITYINDICATORSERVICE_EXCEPTION!= null) {
            throw LOANELIGIBILITYINDICATORSERVICE_EXCEPTION;
        }
        return LOANELIGIBILITYINDICATORSERVICE_WSDL_LOCATION;
    }

}
