
package com.example.soap.ws.client.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LoanEligibilityIndicator", targetNamespace = "http://www.example.com/soap/ws/loanEligibility")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanEligibilityIndicator {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.soap.ws.client.stub.Acknowledgement
     */
    @WebMethod(operationName = "CustomerCheck", action = "http://www.example.com/soap/ws/loanEligibility/CustomerCheck")
    @WebResult(name = "Acknowledgement", targetNamespace = "http://www.example.com/soap/ws/loanEligibility", partName = "parameters")
    public Acknowledgement customerCheck(
        @WebParam(name = "CustomerRequest", targetNamespace = "http://www.example.com/soap/ws/loanEligibility", partName = "parameters")
        CustomerRequest parameters);

}
